# Generated by Django 4.2.12 on 2024-06-10 10:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0020_variants_update'),
        ('order', '0002_cuopon_order_discount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemlOrder',
            new_name='ItemOrder',
        ),
    ]
