# Generated by Django 4.2.12 on 2024-06-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_itemlorder_itemorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cuopon',
            new_name='Coupon',
        ),
    ]
