# Generated by Django 4.2.12 on 2024-05-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_creat_product_create_product_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_price',
        ),
    ]
