# Generated by Django 4.2.12 on 2024-05-22 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_color_size_product_status_variant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variant',
            new_name='Variants',
        ),
    ]
