# Generated by Django 4.2.12 on 2024-05-26 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_variants_color_variant_alter_variants_size_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
