# Generated by Django 4.2.12 on 2024-06-08 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0017_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='unlike',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_unlike', to=settings.AUTH_USER_MODEL),
        ),
    ]
