# Generated by Django 4.2.12 on 2024-06-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_product_category_alter_product_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
